# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: party.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "User" do
    optional :name, :string, 1
  end
  add_message "PartyResp" do
    optional :msg, :string, 1
  end
end

User = Google::Protobuf::DescriptorPool.generated_pool.lookup("User").msgclass
PartyResp = Google::Protobuf::DescriptorPool.generated_pool.lookup("PartyResp").msgclass
