# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: party.proto for package ''

require 'grpc'
require 'party_pb'

module Party
  class Service

    include GRPC::GenericService

    self.marshal_class_method = :encode
    self.unmarshal_class_method = :decode
    self.service_name = 'Party'

    rpc :PartyHard, User, PartyResp
  end

  Stub = Service.rpc_stub_class
end
