# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: party.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='party.proto',
  package='',
  syntax='proto3',
  serialized_pb=_b('\n\x0bparty.proto\"\x14\n\x04User\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x18\n\tPartyResp\x12\x0b\n\x03msg\x18\x01 \x01(\t2)\n\x05Party\x12 \n\tPartyHard\x12\x05.User\x1a\n.PartyResp\"\x00\x62\x06proto3')
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='User.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=35,
)


_PARTYRESP = _descriptor.Descriptor(
  name='PartyResp',
  full_name='PartyResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='PartyResp.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=61,
)

DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['PartyResp'] = _PARTYRESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), dict(
  DESCRIPTOR = _USER,
  __module__ = 'party_pb2'
  # @@protoc_insertion_point(class_scope:User)
  ))
_sym_db.RegisterMessage(User)

PartyResp = _reflection.GeneratedProtocolMessageType('PartyResp', (_message.Message,), dict(
  DESCRIPTOR = _PARTYRESP,
  __module__ = 'party_pb2'
  # @@protoc_insertion_point(class_scope:PartyResp)
  ))
_sym_db.RegisterMessage(PartyResp)



_PARTY = _descriptor.ServiceDescriptor(
  name='Party',
  full_name='Party',
  file=DESCRIPTOR,
  index=0,
  options=None,
  serialized_start=63,
  serialized_end=104,
  methods=[
  _descriptor.MethodDescriptor(
    name='PartyHard',
    full_name='Party.PartyHard',
    index=0,
    containing_service=None,
    input_type=_USER,
    output_type=_PARTYRESP,
    options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PARTY)

DESCRIPTOR.services_by_name['Party'] = _PARTY

try:
  # THESE ELEMENTS WILL BE DEPRECATED.
  # Please use the generated *_pb2_grpc.py files instead.
  import grpc
  from grpc.beta import implementations as beta_implementations
  from grpc.beta import interfaces as beta_interfaces
  from grpc.framework.common import cardinality
  from grpc.framework.interfaces.face import utilities as face_utilities


  class PartyStub(object):
    # missing associated documentation comment in .proto file
    pass

    def __init__(self, channel):
      """Constructor.

      Args:
        channel: A grpc.Channel.
      """
      self.PartyHard = channel.unary_unary(
          '/Party/PartyHard',
          request_serializer=User.SerializeToString,
          response_deserializer=PartyResp.FromString,
          )


  class PartyServicer(object):
    # missing associated documentation comment in .proto file
    pass

    def PartyHard(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.set_code(grpc.StatusCode.UNIMPLEMENTED)
      context.set_details('Method not implemented!')
      raise NotImplementedError('Method not implemented!')


  def add_PartyServicer_to_server(servicer, server):
    rpc_method_handlers = {
        'PartyHard': grpc.unary_unary_rpc_method_handler(
            servicer.PartyHard,
            request_deserializer=User.FromString,
            response_serializer=PartyResp.SerializeToString,
        ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
        'Party', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


  class BetaPartyServicer(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def PartyHard(self, request, context):
      # missing associated documentation comment in .proto file
      pass
      context.code(beta_interfaces.StatusCode.UNIMPLEMENTED)


  class BetaPartyStub(object):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This class was generated
    only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0."""
    # missing associated documentation comment in .proto file
    pass
    def PartyHard(self, request, timeout, metadata=None, with_call=False, protocol_options=None):
      # missing associated documentation comment in .proto file
      pass
      raise NotImplementedError()
    PartyHard.future = None


  def beta_create_Party_server(servicer, pool=None, pool_size=None, default_timeout=None, maximum_timeout=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_deserializers = {
      ('Party', 'PartyHard'): User.FromString,
    }
    response_serializers = {
      ('Party', 'PartyHard'): PartyResp.SerializeToString,
    }
    method_implementations = {
      ('Party', 'PartyHard'): face_utilities.unary_unary_inline(servicer.PartyHard),
    }
    server_options = beta_implementations.server_options(request_deserializers=request_deserializers, response_serializers=response_serializers, thread_pool=pool, thread_pool_size=pool_size, default_timeout=default_timeout, maximum_timeout=maximum_timeout)
    return beta_implementations.server(method_implementations, options=server_options)


  def beta_create_Party_stub(channel, host=None, metadata_transformer=None, pool=None, pool_size=None):
    """The Beta API is deprecated for 0.15.0 and later.

    It is recommended to use the GA API (classes and functions in this
    file not marked beta) for all further purposes. This function was
    generated only to ease transition from grpcio<0.15.0 to grpcio>=0.15.0"""
    request_serializers = {
      ('Party', 'PartyHard'): User.SerializeToString,
    }
    response_deserializers = {
      ('Party', 'PartyHard'): PartyResp.FromString,
    }
    cardinalities = {
      'PartyHard': cardinality.Cardinality.UNARY_UNARY,
    }
    stub_options = beta_implementations.stub_options(host=host, metadata_transformer=metadata_transformer, request_serializers=request_serializers, response_deserializers=response_deserializers, thread_pool=pool, thread_pool_size=pool_size)
    return beta_implementations.dynamic_stub(channel, 'Party', cardinalities, options=stub_options)
except ImportError:
  pass
# @@protoc_insertion_point(module_scope)
